export const tabs = ["Technical Leadership", "Architecture Decisions", "UX Patterns", "User Interface"];

export const decisions = [
  {
    title: "Modular Monolith Instead of Microservices",
    category: "System Architecture",
    summary: "Preserve domain boundaries without paying distributed-system costs too early.",
    context: "The product was growing rapidly, but domain boundaries were still evolving and the engineering team was relatively small.",
    constraints: ["Small team with limited operational bandwidth", "Fast product iteration was more important than independent scaling", "The domain model was still changing"],
    options: ["Microservices", "A tightly coupled monolith", "A modular monolith"],
    decision: "Use a modular monolith with explicit domain boundaries instead of introducing microservices immediately.",
    reasoning: "This keeps deployment and local development simple while making dependencies visible and enforcing separation inside the codebase.",
    tradeoffs: ["Simpler deployment and local debugging", "Strong internal module boundaries", "Less independent scalability", "Shared runtime and release cycle"],
    outcome: "The architecture stays simple while preserving a future path to extract individual modules when operational or scaling pressure justifies it.",
    technologies: ["Domain modules", "TypeScript", "PostgreSQL"],
    diagram: true,
  },
  {
    title: "Progressive Enhancement Over a JavaScript-Only Shell",
    category: "Product Architecture",
    summary: "Make the primary experience resilient before optimizing the richest experience.",
    context: "The interface needed to work across inconsistent devices and network conditions while still feeling immediate for returning users.",
    constraints: ["Unreliable mobile connectivity", "Core workflows needed to remain accessible", "Interactive areas still benefited from client-side state"],
    options: ["Client-render everything", "Server-render everything", "Progressively enhance core flows"],
    decision: "Render meaningful content and navigation first, then layer richer interactions on top where they improve the task.",
    reasoning: "The baseline remains fast and resilient, while JavaScript is spent on interactions that genuinely reduce user effort.",
    tradeoffs: ["More deliberate component boundaries", "Less control over purely client-side transitions", "A stronger baseline on slow connections"],
    outcome: "Users can reach the important content quickly, and enhanced interactions remain available without making them a prerequisite.",
    technologies: ["Next.js", "React", "Web APIs"],
    diagram: false,
  },
];

export const uxPatterns = [
  { title: "Progressive Disclosure", category: "Interaction Design", summary: "Reduce cognitive load by revealing complexity at the moment it becomes useful.", problem: "Administrative workflows often expose every setting at once, making the primary task harder to find.", interaction: "Keep the core action and essential fields visible, then reveal advanced controls without leaving the current context.", reasoning: "This supports fast users without forcing new or occasional users to parse a complete configuration surface upfront.", considerations: ["Keep primary actions visible", "Preserve context when expanding", "Make advanced options discoverable"], edgeCases: ["Remember expanded state during a workflow", "Do not hide frequently used controls", "Keep keyboard focus predictable"], outcome: "Users can complete the common path quickly while retaining access to the depth needed for less frequent scenarios.", preview: "disclosure", project: "School Management SAAS Platform" },
  { title: "Optimistic Interaction", category: "Feedback & State", summary: "Make frequent reversible actions feel immediate while keeping failure recoverable.", problem: "Waiting for a network response after every small action makes an otherwise fluid workflow feel slow.", interaction: "Reflect the expected result immediately, mark the operation as syncing, and provide a clear retry or undo path if it fails.", reasoning: "Perceived responsiveness improves when the interface acknowledges intent before the server finishes, provided the action can be reconciled safely.", considerations: ["Use only for predictable actions", "Show sync status when useful", "Make rollback explicit"], edgeCases: ["Handle duplicate submissions", "Resolve stale server responses", "Restore the previous state after failure"], outcome: "High-frequency interactions feel direct without hiding the system's eventual consistency or failure state.", preview: "sync", project: "LeadingAI: AI-Powered Agentic Chatbot" },
  { title: "Empty States", category: "Product Guidance", summary: "Turn a lack of data into a clear next step instead of a dead end.", problem: "A blank table does not tell a new user whether setup is incomplete, data is filtered, or something failed.", interaction: "Pair a concise explanation with the primary setup action and keep the state distinct from loading and error states.", reasoning: "The empty state is part of the product workflow, especially for new accounts and newly created spaces.", considerations: ["Explain why the state exists", "Offer one primary action", "Respect active filters"], edgeCases: ["Differentiate no results from no data", "Handle permission-limited views", "Keep copy useful after setup"], outcome: "Users understand what they are seeing and what action will make the workspace useful.", preview: "empty", project: "Barnomala - Education Management System" },
  { title: "Error Recovery", category: "Resilient Workflows", summary: "Design failure states around the user's next recovery action.", problem: "A generic error message leaves users unsure whether to retry, edit their input, or contact someone.", interaction: "State what failed, preserve what can be preserved, and offer the smallest useful recovery action in place.", reasoning: "Recovery-oriented errors reduce abandonment and make system boundaries understandable without exposing implementation details.", considerations: ["Preserve entered data", "Use action-specific copy", "Avoid blaming the user"], edgeCases: ["Expired sessions", "Partial writes", "Repeated failures and offline mode"], outcome: "Users can recover from common failures without restarting a workflow or guessing what the system expects.", preview: "error", project: "CMS Project: Learning Health, Emotional, Life Lessons" },
  { title: "Complex Forms", category: "Workflow Design", summary: "Make long, dependent forms feel manageable without losing data or context.", problem: "Multi-step forms combine validation, dependencies, partial completion, and potentially destructive changes.", interaction: "Group fields by user intent, validate close to the source, autosave meaningful progress, and make dependencies explicit.", reasoning: "A form is a workflow rather than a collection of inputs; its structure should help users build confidence as they go.", considerations: ["Validate at the right moment", "Show progress and saved state", "Confirm destructive actions"], edgeCases: ["Browser refreshes", "Conditional fields becoming invalid", "Partial completion across devices"], outcome: "Users can pause, correct, and resume complex tasks with less anxiety and fewer lost inputs.", preview: "form", project: "School Management SAAS Platform" },
];

export const uiPatterns = [
  { title: "Data Table System", category: "Data Interfaces", summary: "Keep dense operational data understandable as filtering, sorting, and bulk actions grow.", problem: "Administrators need to scan and act on many records without losing their place or the meaning of each row.", interface: "Use a clear toolbar, semantic columns, compact row actions, and a responsive priority order for information.", features: ["Search and filters", "Sorting and pagination", "Row selection and bulk actions"], states: ["Loading", "Empty", "Filtered no results", "Error"], responsiveBehavior: "On smaller screens, preserve essential identity and status while moving secondary actions into a contextual menu.", accessibility: "Use semantic table structure, visible focus states, keyboard-operable selection, and explicit action labels.", technologies: ["Vue", "Laravel", "Tailwind CSS"], designSystem: "12px spacing rhythm · compact density · status tokens", project: "School Management SAAS Platform", preview: "table" },
  { title: "Form System", category: "Input & Validation", summary: "Create consistent forms that communicate field state, dependencies, and submission feedback.", problem: "Repeated forms drift when labels, validation timing, and success or failure behavior are implemented ad hoc.", interface: "Build around reusable field primitives with clear labels, helper text, inline validation, and a stable action area.", features: ["Field-level validation", "Dependent fields", "Autosave and submission feedback"], states: ["Default", "Focus", "Error", "Disabled", "Success"], responsiveBehavior: "Collapse multi-column groups into a readable single flow while keeping the primary action reachable.", accessibility: "Associate labels and errors programmatically, preserve focus after validation, and never rely on color alone.", technologies: ["React", "Next.js", "Reusable primitives"], designSystem: "16px field rhythm · shared focus ring · consistent validation language", project: "Barnomala - Education Management System", preview: "form" },
  { title: "Dashboard Interface", category: "Information Hierarchy", summary: "Turn multiple signals into a dashboard that supports scanning first and investigation second.", problem: "A dashboard can become a wall of equally weighted metrics with no clear starting point or next action.", interface: "Lead with a small set of decision-relevant metrics, group related detail, and use progressive depth for investigation.", features: ["Metric hierarchy", "Contextual trends", "Actionable exceptions"], states: ["Partial data", "Loading", "Stale data", "Permission-limited"], responsiveBehavior: "Reorder metrics by decision value and stack detail panels instead of shrinking every chart.", accessibility: "Provide text alternatives for charts, logical heading order, and summaries that do not depend on visual comparison.", technologies: ["Next.js", "Recharts", "Responsive CSS"], designSystem: "Surface hierarchy · 8px spacing base · restrained accent color", project: "LeadingAI: AI-Powered Agentic Chatbot", preview: "dashboard" },
  { title: "Navigation System", category: "Information Architecture", summary: "Make primary, contextual, and mobile navigation feel like one coherent system.", problem: "Users lose orientation when desktop menus, breadcrumbs, and mobile navigation expose different mental models.", interface: "Use stable primary destinations, contextual location cues, and a mobile pattern that preserves orientation while reducing chrome.", features: ["Active location", "Breadcrumbs", "Mobile navigation"], states: ["Active", "Expanded", "Collapsed", "Keyboard focus"], responsiveBehavior: "Move secondary destinations behind a labeled menu while keeping the current location and primary route visible.", accessibility: "Use landmarks, skip links, current-page semantics, and predictable keyboard focus when menus open or close.", technologies: ["Next.js", "React", "Semantic HTML"], designSystem: "Consistent hit areas · focus ring token · route-aware states", project: "CMS Project: Learning Health, Emotional, Life Lessons", preview: "navigation" },
  { title: "Design Tokens", category: "Visual Foundations", summary: "Use shared visual rules to make individual components feel like one product, not isolated screens.", problem: "Small inconsistencies in spacing, type, color, and focus treatment compound as a product grows.", interface: "Define a limited vocabulary for surfaces, text, accents, spacing, borders, and interaction states before composing screens.", features: ["Color and surface roles", "Type hierarchy", "Spacing and focus tokens"], states: ["Light theme", "Dark theme", "Hover", "Focus"], responsiveBehavior: "Keep the system stable across breakpoints and change layout rules rather than inventing new visual values.", accessibility: "Check contrast by semantic role and ensure focus and disabled states remain visible in every theme.", technologies: ["CSS variables", "Tailwind CSS", "Theme context"], designSystem: "Primary accent · gradient surfaces · shared typography variables", project: "Portfolio website", preview: "tokens" },
  { title: "Accessible Component States", category: "Inclusive Interfaces", summary: "Treat focus, disabled, error, and reduced-motion behavior as part of the component contract.", problem: "A component that only looks correct in its default state can become confusing or unusable during real interaction.", interface: "Design state transitions deliberately and make feedback visible, understandable, and consistent across components.", features: ["Keyboard interaction", "Focus management", "Screen-reader feedback"], states: ["Focus-visible", "Disabled", "Busy", "Error", "Success"], responsiveBehavior: "Maintain usable hit areas and readable state text even when controls stack or move into compact layouts.", accessibility: "Use semantic controls, announce dynamic status when needed, support reduced motion, and test without a mouse.", technologies: ["React", "ARIA", "Framer Motion"], designSystem: "State-first primitives · semantic status colors · visible focus", project: "LeadingAI: AI-Powered Agentic Chatbot", preview: "states" },
];

export const leadershipPractices = [
  {
    title: "Technical Decision Making",
    category: "Engineering Practice",
    summary: "Turn competing implementation options into a decision the team can understand, execute, and revisit.",
    context: "A growing product had several plausible architectural directions, but team size, delivery speed, and changing domain boundaries limited how much operational complexity it could absorb.",
    approach: "Frame the options around constraints, document the trade-offs, and make the chosen boundary explicit before implementation expands.",
    role: "Technical ownership and team-level influence: I structured the decision and provided the rationale without presenting it as a management mandate.",
    impact: ["Reduced ambiguity during implementation", "Kept operational complexity proportional to current needs", "Created a reference for future architecture discussions"],
    lessons: "A good decision records why an option fit the moment, not just what the team selected.",
    project: "School Management SAAS Platform",
    relatedDecision: "Modular Monolith Instead of Microservices",
    caseStudyLink: "#project",
    visual: "decision",
  },
  {
    title: "Architecture Communication",
    category: "Technical Alignment",
    summary: "Make system boundaries and trade-offs legible to the people who depend on them.",
    context: "When a product spans interface, domain, and data concerns, unclear boundaries create duplicate logic and make changes harder to coordinate.",
    approach: "Use concise diagrams, plain-language explanations, and decision records that connect technical constraints to product consequences.",
    role: "Cross-functional collaboration: I translated implementation consequences for engineers and non-technical stakeholders so discussion could focus on shared constraints.",
    impact: ["Improved alignment around ownership boundaries", "Made dependencies easier to spot", "Reduced the need to rediscover architectural context"],
    lessons: "Communication is part of the architecture when it changes how safely a team can work inside it.",
    project: "Portfolio website",
    relatedDecision: "Progressive Enhancement Over a JavaScript-Only Shell",
    caseStudyLink: "#project",
    visual: "communication",
  },
  {
    title: "Code Review & Engineering Standards",
    category: "Quality Practice",
    summary: "Use review as a way to improve correctness, maintainability, and shared technical judgment.",
    context: "As similar workflows multiply, inconsistent validation, state handling, and component structure make future work slower and harder to reason about.",
    approach: "Review for behavior and boundaries first, identify reusable patterns, and turn recurring feedback into conventions or shared primitives.",
    role: "Technical ownership and mentoring: I used concrete implementation feedback to raise consistency while leaving room for engineers to own their solutions.",
    impact: ["More predictable behavior across related features", "Less repeated review feedback", "Better transfer of implementation context across the team"],
    lessons: "Standards work best when they remove repeated decisions rather than adding ceremony for its own sake.",
    project: "Barnomala - Education Management System",
    relatedDecision: "Progressive Enhancement Over a JavaScript-Only Shell",
    caseStudyLink: "#project",
    visual: "review",
  },
  {
    title: "Mentoring Through Technical Context",
    category: "Developer Growth",
    summary: "Help engineers build judgment by making the reasoning behind implementation choices visible.",
    context: "Developers move faster when they understand not only how a feature works, but also which constraints and failure modes shaped it.",
    approach: "Explain the decision space, ask questions that surface assumptions, and pair on the smallest useful slice before handing ownership back.",
    role: "Mentoring and collaborative problem solving: I supported engineers through context and feedback rather than taking over their implementation.",
    impact: ["Increased confidence with unfamiliar parts of the system", "Encouraged engineers to evaluate trade-offs independently", "Built more durable ownership of features"],
    lessons: "The goal of mentoring is not to provide the fastest answer; it is to make the next answer easier to find.",
    project: "LeadingAI: AI-Powered Agentic Chatbot",
    relatedDecision: "Modular Monolith Instead of Microservices",
    caseStudyLink: "#project",
    visual: "mentoring",
  },
  {
    title: "Technical Documentation",
    category: "Knowledge Systems",
    summary: "Capture decisions and implementation context where future contributors can use them.",
    context: "Important reasoning disappears when it lives only in conversations, making onboarding and later changes depend on memory.",
    approach: "Write focused decision records, implementation notes, and diagrams close to the code or workflow they explain.",
    role: "Technical ownership: I shaped the reference material and connected it to decisions, while keeping documentation practical to maintain.",
    impact: ["Made onboarding and handoffs less dependent on oral history", "Enabled decisions to be revisited with their original context", "Reduced repeated explanation across project work"],
    lessons: "Documentation earns its place when it shortens a future decision or prevents a known mistake.",
    project: "CMS Project: Learning Health, Emotional, Life Lessons",
    relatedDecision: "Progressive Enhancement Over a JavaScript-Only Shell",
    caseStudyLink: "#project",
    visual: "documentation",
  },
  {
    title: "Engineering Process Improvement",
    category: "Delivery Practice",
    summary: "Remove recurring development friction by improving the workflow around the code.",
    context: "Repeated manual checks, unclear states, and inconsistent handoffs create delivery cost even when individual features are straightforward.",
    approach: "Look for patterns in failures and rework, then improve the smallest useful part of the workflow through conventions, tooling, or clearer feedback.",
    role: "Team-level influence: I identified friction, proposed practical changes, and helped validate them in real project work.",
    impact: ["Made common workflows easier to repeat", "Improved feedback before work reached users", "Freed attention for product and technical decisions"],
    lessons: "Process improvement should be measured by reduced friction in real work, not by the number of new rules introduced.",
    project: "School Management SAAS Platform",
    relatedDecision: "Progressive Enhancement Over a JavaScript-Only Shell",
    caseStudyLink: "#project",
    visual: "process",
  },
];