"use client";
import "./globals.css";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Roboto } from "next/font/google";
const roboto = Roboto({ weight: "400", subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const router = useRouter();
  // const isActive = pathname.startsWith("/profile")

  return (
    <html lang="en">
      <body className={roboto.className}>
        <div>
          <Link
            href="/profile"
            className={pathname === "/profile" ? "active" : ""}
          >
            Profile
          </Link>
          <button onClick={() => router.push("/")}>Home</button>
        </div>
        {children}
      </body>
    </html>
  );
}
